### ISSUE TITLE
Possible to advertise positions on libretexts.org?

### ISSUE THREAD

**Issue by moorepants** [LibreTexts/NewSite#2]
I have these postings that i want to fill by Jan 31:

https://mechmotum.github.io/jobs.html

Can we have a "jobs" listing on the libretexts site?

**Comment by Miniland1333** [comment]
I think that the libretexts site is too general to have a job listings on it since I assume you want UCD students only. I can ask Delmar for his opinion or if he has a recommendation for a more UCD-specific location.

BTW, do you have a preferred Kubernetes provider? We are using DO for a few servers currently but nothing binding.

**Comment by moorepants** [comment]
I don't know about a kubernetes provider. FYI, we are going to run our own cluster and not use cloud services for all the jupyter related things we will run on top of kubernetes. I have support from the CS chair and the bioinformatics core to get that all set up.

I'll close this and advertise myself. Thanks.

**Comment by Miniland1333** [comment]
Let me know if you end up using any cloud services, since I only have experience with DigitalOcean's services at the moment and I want to know more about other offerings.

Also let me know when you need DNS records created to point at your jupyter projects!
